### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by kosei-tanoue** [kosei-tanoue/furima-29610#10]
# フリマアプリのURL
https://furima-29610.herokuapp.com/

# Basic認証のIDとパスワード
ID admin 
パスワード 2222

# 出品者用のメールアドレスとパスワード
出品者 ふ
メールアドレス f@f2
パスワード aaaa1111

# 購入者用のメールアドレスとパスワード
購入者 trrrrrrrrr
メールアドレス t@1
パスワード aaaa1111

# 購入用カードの番号・期限・セキュリティコード
カード番号 4242424242424242
期限 今より未来なら問題なし
セキュリティコード 123

**Comment by pikifre3** [comment]
この度は、大変遅くなりまして申しわけございませんでした。

ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。
